[package]
name = "phoxal-robot-project"
version = "0.0.0-dev.1"
edition = "2024"
rust-version = "1.88"
publish = false
license = "MIT"

[workspace]
resolver = "3"

[workspace.dependencies]
anyhow = "1"
phoxal = { registry = "phoxal", version = "=0.0.0-dev.2" }
phoxal-supervisor = { registry = "phoxal", version = "=0.0.0-dev.2" }
ddsm115 = { package = "phoxal-component-ddsm115", registry = "phoxal", version = "=0.0.0-dev.2" }
vl53l1x = { package = "phoxal-component-vl53l1x", registry = "phoxal", version = "=0.0.0-dev.2" }

kinematics = { package = "phoxal-service-kinematics", registry = "phoxal", version = "=0.0.0-dev.2" }
world = { package = "phoxal-service-world", registry = "phoxal", version = "=0.0.0-dev.2" }
safety = { package = "phoxal-service-safety", registry = "phoxal", version = "=0.0.0-dev.2" }
motion = { package = "phoxal-service-motion", registry = "phoxal", version = "=0.0.0-dev.2" }

prost = "0.14.4"
serde_json = "1"

[dependencies]
anyhow.workspace = true
phoxal.workspace = true
phoxal-supervisor.workspace = true
ddsm115.workspace = true
vl53l1x.workspace = true

kinematics.workspace = true
world.workspace = true
safety.workspace = true
motion.workspace = true
prost.workspace = true
serde_json.workspace = true

[profile.dev.package.sha2]
opt-level = 3

[[test]]
name = "phoxal-scenarios"
path = ".phoxal/generated/scenarios/main.rs"
harness = false
test = false

[dev-dependencies]
clap = { version = "4.6.1", features = ["derive"] }
phoxal = { registry = "phoxal", version = "=0.0.0-dev.2", features = ["scenario", "port"] }
