[package]
name = "phoxal-scenario-forward-turn-stop2"
version = "0.0.0"
edition = "2024"
publish = false
description = "Rover canonical scenario variant: forward, turn right, stop."

[lib]
path = "mod.rs"

[dependencies]
phoxal = { path = "/Users/jbernavaprah/RustroverProjects/phoxal/framework/phoxal", features = ["scenario"] }